export const EDITOR_ADD_LINE = 'EDITOR ADD LINE'
export const EDITOR_REMOVE_LINE = 'EDITOR REMOVE LINE'
export const EDITOR_LINE_CHANGE = 'EDITOR LINE CHANGE'
export const EDITOR_PREVIEW = 'EDITOR PREVIEW'

export const LINE_CHANGE = 'LINE CHANGED'
