export const EDITOR_ADD_LINE = 'EDITOR ADD LINE'
export const EDITOR_REMOVE_LINE = 'EDITOR REMOVE LINE'
export const EDITOR_LINE_CHANGE = 'EDITOR LINE CHANGE'
export const EDITOR_PREVIEW = 'EDITOR PREVIEW'
export const EDITOR_PUBLISH = 'EDITOR PUBLISH'
export const EDITOR_TITLE_CHANGE = 'EDITOR TITLE CHANGE'

export const LINE_CHANGE = 'LINE CHANGED'
export const LINE_TRANSITION_UPDATE = 'LINE TRANSITION UPDATED'
export const LINE_DELAY_UPDATE = 'LINE DELAY UPDATED'
export const LINE_PROP_UPDATE = 'LINE PROPERTY UPDATED'

export const POPOVER_TOGGLE = 'POPOVER TOGGLED'
